Name: NAGARAMPALLI SARVAN KUMAR

Roll Number: CH.SC.U4CSE24130

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
data = pd.read_csv('01-linear-regression-dataset-task-1.csv')

In [3]:
data.head()

,unique_key,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,...,extras,trip_total,payment_type,company,pickup_latitude,pickup_longitude,pickup_location,dropoff_latitude,dropoff_longitude,dropoff_location
0,b99416692f5bc01cdb444cbcec7e1105d30d455d,8dd990653cc2793d96b80ae45e928afc9a590b21b491ee...,5/29/2019 18:00:00,5/29/2019 18:30:00,1500.0,1.50,NaN,NaN,NaN,NaN,...,0.0,12.36,Credit Card,KOAM Taxi Association,NaN,NaN,NaN,NaN,NaN,NaN
1,b99887012c8beccc1dae3f6fcde2fc94ff0ef7b1,d156d4adff01addd62b65753ce67dc8e04bdaf60f7eb14...,5/20/2019 19:15:00,5/20/2019 19:30:00,506.0,1.67,NaN,NaN,NaN,NaN,...,0.0,10.50,Credit Card,Chicago Carriage Cab Corp,NaN,NaN,NaN,NaN,NaN,NaN
2,b98b6b7afe1f8065d8ba71cd023d9a13f2460f84,beefd3462e3f5a8e854942a2796876f6db73ebbd25b435...,5/8/2019 0:00:00,5/8/2019 0:00:00,60.0,0.00,NaN,NaN,NaN,NaN,...,0.0,3.25,Cash,Taxi Affiliation Services,NaN,NaN,NaN,NaN,NaN,NaN
3,b9865af3673441b1a79973ad08bd9909bd422af4,ef249ea2c31ccb20ce9eb258d3116254a6f9fe05c7cc84...,5/7/2019 16:30:00,5/7/2019 17:00:00,1122.0,2.86,NaN,NaN,NaN,NaN,...,1.0,13.25,Cash,Taxi Affiliation Service Yellow,NaN,NaN,NaN,NaN,NaN,NaN
4,e04dbd9a8ba723cc785c4b0398106b72e16d7870,45002471b85d61e62cf602a15145d2bff912e080f50470...,5/16/2013 8:15:00,5/16/2013 8:15:00,NaN,0.00,NaN,NaN,NaN,NaN,...,0.0,30.06,Credit Card,Chicago Elite Cab Corp.,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data.shape

(500, 23)

In [5]:
data = data.dropna(subset=['trip_seconds', 'trip_miles', 'fare'])

In [6]:
data['Payment_Card'] = data['payment_type'].map(lambda p: 1 if p == 'Credit Card' else 0)

In [7]:
data.head()

,unique_key,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,...,trip_total,payment_type,company,pickup_latitude,pickup_longitude,pickup_location,dropoff_latitude,dropoff_longitude,dropoff_location,Payment_Card
0,b99416692f5bc01cdb444cbcec7e1105d30d455d,8dd990653cc2793d96b80ae45e928afc9a590b21b491ee...,5/29/2019 18:00:00,5/29/2019 18:30:00,1500.0,1.50,NaN,NaN,NaN,NaN,...,12.36,Credit Card,KOAM Taxi Association,NaN,NaN,NaN,NaN,NaN,NaN,1
1,b99887012c8beccc1dae3f6fcde2fc94ff0ef7b1,d156d4adff01addd62b65753ce67dc8e04bdaf60f7eb14...,5/20/2019 19:15:00,5/20/2019 19:30:00,506.0,1.67,NaN,NaN,NaN,NaN,...,10.50,Credit Card,Chicago Carriage Cab Corp,NaN,NaN,NaN,NaN,NaN,NaN,1
2,b98b6b7afe1f8065d8ba71cd023d9a13f2460f84,beefd3462e3f5a8e854942a2796876f6db73ebbd25b435...,5/8/2019 0:00:00,5/8/2019 0:00:00,60.0,0.00,NaN,NaN,NaN,NaN,...,3.25,Cash,Taxi Affiliation Services,NaN,NaN,NaN,NaN,NaN,NaN,0
3,b9865af3673441b1a79973ad08bd9909bd422af4,ef249ea2c31ccb20ce9eb258d3116254a6f9fe05c7cc84...,5/7/2019 16:30:00,5/7/2019 17:00:00,1122.0,2.86,NaN,NaN,NaN,NaN,...,13.25,Cash,Taxi Affiliation Service Yellow,NaN,NaN,NaN,NaN,NaN,NaN,0
5,b997997e971c079dd0986102def2de49e879efe5,fa0a84435b292833f8429400e94600f4b71dd17cafbaf5...,5/24/2019 13:15:00,5/24/2019 13:15:00,240.0,1.40,NaN,NaN,NaN,NaN,...,5.20,Cash,Taxi Affiliation Services,NaN,NaN,NaN,NaN,NaN,NaN,0

In [8]:
X = data[['trip_miles', 'trip_seconds', 'Payment_Card']]
y = data['fare']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [11]:
predictions = model.predict(X_test)

In [12]:
print("Actual vs Predicted Fares")
print("---------------------------")
comparison_df = pd.DataFrame({
    'Actual Fare': y_test.values,
    'Predicted Fare': predictions
})
print(comparison_df)

Actual vs Predicted Fares
---------------------------
    Actual Fare  Predicted Fare
0         13.00       11.054762
1          9.25       11.054762
2          4.50        8.538511
3         31.00       34.109787
4         32.00       11.054762
..          ...             ...
92        31.75       30.783105
93         8.00       14.783486
94        98.00       11.109576
95         7.00       13.544643
96        14.00       14.995270

[97 rows x 2 columns]

In [13]:
mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("Regression Evaluation Metrics")
print("---------------------------")
print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Squared Error (MSE):  {mse:.2f}")
print(f"R-squared Score (R2):      {r2:.4f}")

Regression Evaluation Metrics
---------------------------
Mean Absolute Error (MAE): 5.30
Mean Squared Error (MSE):  109.20
R-squared Score (R2):      0.6130